baseURL = 'https://nickkust-portfolio.netlify.app'
theme = "hello-friend-ng"
defaultContentLanguage = "en"
languageCode = "en-us"
title = "Nick Kust"

[pagination]
pagerSize = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Head of Product at Future Present Labs"

  # Set disableReadOtherPosts to true if you don't want to display links to other posts
  disableReadOtherPosts = false

  # Enable theme toggle
  enableThemeToggle = true

  # Enable sharing buttons
  EnableSharingButtons = true

  # Global language menu
  disableGlobalLanguageMenu = false

  # Custom CSS
  customCSS = []

  # Custom JS
  customJS = []

  # Description for SEO
  description = "Nick Kust - Head of Product at Future Present Labs. Economist, builder, and product thinker."
  keywords = "product management, economics, manufacturing, technology"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Nick Kust"
    subtitle = "Head of Product at Future Present Labs"
    keywords = ""
    copyright = '<span style="display: inline-block;">Â© 2026 Nick Kust</span>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Nick Kust"
      logoHomeLink = "/"

    [[languages.en.menu.main]]
      identifier = "about"
      name       = "About"
      url        = "/about/"
      weight     = 1

    [[languages.en.menu.main]]
      identifier = "posts"
      name       = "Posts"
      url        = "/posts/"
      weight     = 2

[params.portrait]
  path     = "/img/avatar.png"
  alt      = "Nick Kust"
  maxWidth = "300px"

# Social icons
[[params.social]]
  name = "linkedin"
  url  = "https://linkedin.com/in/nickkust"

[[params.social]]
  name = "github"
  url  = "https://github.com/nickkust"

[[params.social]]
  name = "twitter"
  url  = "https://twitter.com/nickkust"
