baseURL = 'https://nickkust-portfolio.netlify.app'
languageCode = 'en-us'
title = 'Nick Kust'
theme = 'PaperMod'

[params]
  author = 'Nick Kust'
  description = 'Head of Product at Future Present Labs. Economist, builder, and product thinker.'
  defaultTheme = 'dark'
  disableThemeToggle = false
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = true
  tocopen = false
  
  customCSS = ["css/extended/custom.css"]

  [params.profileMode]
    enabled = true
    title = 'Nick Kust'
    subtitle = 'Head of Product at Future Present Labs. Economist, builder, and product thinker.'
    imageUrl = '/images/profile.jpg'
    imageWidth = 220
    imageHeight = 220
    imageTitle = 'Nick Kust'

    [[params.profileMode.buttons]]
      name = 'About'
      url = 'about'
    [[params.profileMode.buttons]]
      name = 'Blog'
      url = 'posts'
    [[params.profileMode.buttons]]
      name = 'Contact'
      url = 'contact'

  [params.homeInfoParams]
    Title = "Hi, I'm Nick ðŸ‘‹"
    Content = "Head of Product at [Future Present Labs](https://futurepresentlabs.com). I write about product, economics, and building things that matter."

  [[params.socialIcons]]
    name = 'linkedin'
    url = 'https://linkedin.com/in/nickkust'
  [[params.socialIcons]]
    name = 'github'
    url = 'https://github.com/nickkust'
  [[params.socialIcons]]
    name = 'twitter'
    url = 'https://twitter.com/nickkust'

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about/'
    weight = 20
  [[menu.main]]
    identifier = 'posts'
    name = 'Blog'
    url = '/posts/'
    weight = 30
  [[menu.main]]
    identifier = 'contact'
    name = 'Contact'
    url = '/contact/'
    weight = 40

[taxonomies]
  category = 'categories'
  tag = 'tags'
  series = 'series'

[outputs]
  home = ['HTML', 'RSS', 'JSON']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = 'monokai'
    lineNos = true
    codeFences = true
    guessSyntax = true
    noClasses = false
